version: '3.9'

services:
  backend:
    container_name: backend
    build:
      context: ./backend/
      dockerfile: Dockerfile
    restart: on-failure
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
    networks:
        - jsf-network

  frontend:
    container_name: frontend 
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    restart: on-failure
    ports:
      - "3000:3000"
    env_file:
      - ./frontend/.env
    volumes:
      - ./frontend:/app
    networks:
      - jsf-network

networks:
  jsf-network: 